# Local Attachment with DGL

#### Example Notebook for creating random graph edges (or local attachment) using Deep Graph Library (DGL) for agent based modelling

Import libraries and loading sample DGL graph from previous work

In [1]:
import os

In [2]:
os.environ["DGLBACKEND"] = "pytorch"

In [3]:
import torch 
import pandas as pd
import dgl
from dgl.data import DGLDataset
import dgl.function as fn
import numpy as np

In [4]:
ds = dgl.data.CSVDataset('./DGL_playground/toy_dataset/')

Done loading data from cached files.


In [5]:
g = ds[0]

In [6]:
print(g)

Graph(num_nodes=10, num_edges=20,
      ndata_schemes={' na2': Scheme(shape=(), dtype=torch.int64), ' na1': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'ea2': Scheme(shape=(), dtype=torch.int64), 'ea1': Scheme(shape=(), dtype=torch.int64), 'w': Scheme(shape=(), dtype=torch.int64)})


In [7]:
g.edges()

(tensor([0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8]),
 tensor([1, 2, 3, 0, 2, 0, 1, 0, 4, 5, 3, 5, 3, 4, 7, 8, 6, 8, 6, 7]))

AddEdge adds edges randomly to the graph. For more details on the method, refer [here](https://docs.dgl.ai/generated/dgl.transforms.AddEdge.html?highlight=addedge#dgl.transforms.AddEdge)

AddReverse adds the reverse edges for all existing edges on the graph. For more details on the method, refer [here](https://docs.dgl.ai/generated/dgl.transforms.AddReverse.html). Note that AddReverse does not check for duplicate edges but rather adds a reverse edge for every existing edge.

In [35]:
from dgl import AddEdge, AddReverse

In [17]:
# ratio defines number of new edges to add as a proportion of existing edges. 
# Here we want to add as many edges as number of nodes
ratio = g.num_nodes()/g.num_edges()

In [22]:
new_g = AddEdge(ratio=ratio)(g)

In [23]:
new_g.edges()

(tensor([0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 3, 3, 9, 8,
         5, 1, 3, 8, 5, 7]),
 tensor([1, 2, 3, 0, 2, 0, 1, 0, 4, 5, 3, 5, 3, 4, 7, 8, 6, 8, 6, 7, 5, 9, 1, 0,
         9, 8, 8, 5, 8, 8]))

In [25]:
new_g2 = AddReverse()(new_g)

In [29]:
new_g2.edges()

(tensor([0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 3, 3, 9, 8,
         5, 1, 3, 8, 5, 7, 1, 2, 3, 0, 2, 0, 1, 0, 4, 5, 3, 5, 3, 4, 7, 8, 6, 8,
         6, 7, 5, 9, 1, 0, 9, 8, 8, 5, 8, 8]),
 tensor([1, 2, 3, 0, 2, 0, 1, 0, 4, 5, 3, 5, 3, 4, 7, 8, 6, 8, 6, 7, 5, 9, 1, 0,
         9, 8, 8, 5, 8, 8, 0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7,
         8, 8, 3, 3, 9, 8, 5, 1, 3, 8, 5, 7]))

to_simple function removes duplicate edges from the graph

In [31]:
new_g3 = dgl.to_simple(new_g2, return_counts='cnt')
new_g3.edges()

(tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 6, 6, 7,
         7, 8, 8, 8, 8, 8, 8, 9, 9, 9]),
 tensor([1, 2, 3, 8, 0, 2, 8, 9, 0, 1, 0, 4, 5, 8, 9, 3, 5, 3, 4, 8, 9, 7, 8, 6,
         8, 0, 1, 3, 5, 6, 7, 1, 3, 5]))